import Footer from "@/components/ui/Footer";
import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import Navbar from "@/components/layout/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
     <main >
          {children}
        </main>
      <Footer/>
      </body>

    </html>
  );
}
